# Generated by Django 5.2.16 on 2026-07-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('venue', models.CharField(max_length=100)),
                ('toss_winner', models.CharField(max_length=50)),
                ('toss_decision', models.CharField(max_length=10)),
            ],
        ),
    ]
